### ISSUE TITLE
Option to change background color

### ISSUE THREAD

**Issue by nbb1967** [BLumia/pineapple-pictures#105]
Feature request: Option to change background color.
Light or dark background - these are preferences...

**Comment by BLumia** [comment]
If you hold the <kbd>shift</kbd> key and click the grid button, the grid will be in a lighter color. Just in case you might need this.

That will be much faster than go to the setting dialog and tick an option there.

**Comment by BLumia** [comment]
I might have misunderstood your original request.

If you are looking for a light-color app background instead of the checkerboard, I currently don't have such plans to support this feature.

Luckly, there is a fork that is focus on light-theme support, you can try the fork at here:

- https://github.com/yyc12345/pineapple-pictures/releases/tag/0.8.1
