### ISSUE TITLE
save window position and window size

### ISSUE THREAD

**Issue by super-lurker** [BLumia/pineapple-pictures#12]
save window position and window size

**Comment by BLumia** [comment]
I guess this will be a won't fix type of issue, since currently the application is designed to be associated with image type files so double-clicking image file will launch this application and pass the file path as an argument.

When the application launched with files passed via arguments, the window size will be adjusted by the given image file size. So the window size will always be different depends on your image files, remember the window size/position will be useless to me.

**Comment by BLumia** [comment]
Would like to close this one since no feedback. I still don't think it's valid to remember window size since the window size will be adjusted automatically when launching this application with an image file passed via argument. If anyone would like to see this feature implemented, please consider [starting a new discussion thread](https://github.com/BLumia/pineapple-pictures/discussions) so we could discuss the correct behavior first :)
