### ISSUE TITLE
Option to change mouse scroll for switch images (or full setting for key bindings)

### ISSUE THREAD

**Issue by Seryi3** [BLumia/pineapple-pictures#20]

**Comment by BLumia** [comment]
An option to change mouse wheel behavior is added to the setting dialog in https://github.com/BLumia/pineapple-pictures/commit/1449844fdd084bcc20ea53384618e731be3b049e . You can download the CI build to try it out if you like. 

The full setting for key bindings can be added but may not be added in the next few updates, but since that commit implemented the basic feature request for modifying the wheel behavior, I'll close this issue now :)
