### ISSUE TITLE
Add support for APNG

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [BLumia/pineapple-pictures#44]
This could be done by integrating [libpng-apng](https://sourceforge.net/projects/libpng-apng/).

----

Edited by maintainer:

- [x] QtApng: Should support `DecideFormatFromContent(true)` https://github.com/Skycoder42/QtApng/pull/12
- [x] QtApng: Should return proper image size(resolution) https://github.com/Skycoder42/QtApng/pull/14
- [x] QtApng: Should return PNG as format if it's handling a regular PNG file https://github.com/Skycoder42/QtApng/pull/15
- [ ] Pineapple Pictures (releasing): Do separated binary release that include the APNG image formats plugin.

**Comment by BLumia** [comment]
Adding the third-party APNG Qt image format plugin [QtApng](https://github.com/Skycoder42/QtApng) could be a solution. Since it's likely a packaging/distributing issue, maybe I'll do it in the future but no promise. Feel free to send a PR if anyone would like to working on that :)

**Comment by BLumia** [comment]
Hi, for now, you could now download a test CI build for `apng` formatting support from [here](https://ci.appveyor.com/project/BLumia/pineapplepictures/builds/42068648/artifacts) (ps. expire in 30 days so make sure to download it if you need it right now). Please notice in that build, APNG files should use `apng` extension (instead of `png`) to get proper animation playback.

The APNG format support hasn't yet landed to the `master` branch, I may still do some other changes related to this so it's still subject to change :)

**Comment by BLumia** [comment]
Related: https://github.com/Skycoder42/QtApng/pull/12

**Comment by BLumia** [comment]
Also related: https://github.com/Skycoder42/QtApng/pull/14

**Comment by BLumia** [comment]
I've tested the basic functionality of QtApng in the 0.5.4 period. Some work has already been done from my side and related patches are also upstreamed to the original author. I'm still evaluating the APNG support from QtApng to see if there are any additional issues with that plugin, and once I'm happy with the result, APNG support will hopefully get included in the main release of the Windows binary version.

Before that happen, you could get a separate release for APNG (and other additional formats) from [itch.io store](https://blumia.itch.io/pineapple-pictures), the CI builds, or by building the plugin yourself. If you found any issue with the APNG plugin, feel free to let me know by opening another issue or discussion thread :)
