### ISSUE TITLE
dynamic window size / maximize default option / mid-click toggle original size

### ISSUE THREAD

**Issue by Deleted-Account** [BLumia/pineapple-pictures#46]
Thanks for your work.
This lightweight app reminds me a convenient time with google picasa couples of years ago.

Wish it could have these features:

1. dynamic window size based on pic. If pic size is too large, resize it to fit screen based on width/height/view port.
2. option to toggle “maximize” as default whilst open a pic.
3. mid-click to toggle pic's original size (for large and long screenshot pics), then explore from top part, holding right-click to scroll up/down left/right. Then it would be easy to view a large/long pic. (For small pic, mid-click will resize it to view port size)

I'm now using Vieas (a lightweight pic viewer which is obsoleted for years too),
though it has some issues such as opening large webp file error.

Hope one day Pineapple-pictures can be better than Vieas.
Thanks for your work again.

**Comment by BLumia** [comment]
Thanks for the feedback!

> dynamic window size based on pic. If pic size is too large, resize it to fit screen based on width/height/view port.

It already does this but it requires you to associate the program as the default program to open your image file, then when you double-click your image file, the window size will be a proper size according to the given image size.

I've considered also doing this when switching between images, but the window size change will also cause all the buttons on the UI to move to somewhere else which can be a problem if you need to navigate between images fast, so as the result I decided to not do this.

> option to toggle “maximize” as default whilst open a pic.

That sounds like a proper option to introduce, will consider adding this. Please let me know if anyone also thinks it could be useful if we add this feature :)

> mid-click to toggle pic's original size (for large and long screenshot pics), then explore from top part, holding right-click to scroll up/down left/right. Then it would be easy to view a large/long pic. (For small pic, mid-click will resize it to view port size)

A long-image mode is considered but the final UX is not yet decided. Thanks for the feedback :)

**Comment by BLumia** [comment]
The ability to set startup size to maximize is merged, but the setting option won't be there in the 0.6.0 release since the related copywriting is not finished.

If you want to get a version with such feature now, you can download a CI build at [here](https://ci.appveyor.com/project/BLumia/pineapplepictures/builds/43113375) which is a CI build of the revision https://github.com/BLumia/pineapple-pictures/commit/4babf20427cd7af9e55eba665b45447e655ec6c4.

The option will be included in 0.6.1 release. If you have suggestions about the final copywriting of that option, please feel free to let me know :)
