### ISSUE TITLE
Some svg display exceptions

### ISSUE THREAD

**Issue by xmuli** [BLumia/pineapple-pictures#50]
Found an svg image that did not display successfully; But the rest of the svg works fine

**env**
Pineapple View Version: 0.5.4-0-g00168a3 
win10: 21H2

The result that should be displayed is  https://upload.wikimedia.org/wikipedia/commons/1/1b/Portable_Executable_32_bit_Structure_in_SVG_fixed.svg
![Portable_Executable_32_bit_Structure_in_SVG_fixed](https://user-images.githubusercontent.com/33887845/152914596-4d9978bd-cd08-4d9a-924f-d56fe4aed389.svg)

The actual display exception result is
![20220208_113726](https://user-images.githubusercontent.com/33887845/152914271-29d2523b-d389-41f3-b035-2141dde1f6f2.png)
![20220208_113734](https://user-images.githubusercontent.com/33887845/152914276-f419614b-0fd3-41e4-92b0-a1805d82893e.png)

**Comment by BLumia** [comment]
Currently, SVG support is powered by Qt's SVG module, which only supports the static features of SVG 1.2 Tiny standard, and ECMA scripts and DOM manipulation are currently not supported. There might be other drop-in replacements for Qt SVG rendering, not sure about it.

I don't have any plan to provide other SVG standard supports. For complex SVG files please consider using a browser, since it can be crazy to get a "real" proper SVG rendering result, and feel free to find other solutions ;p

**Comment by xmuli** [comment]
I forgot that qsvg only supports a subset of svg😥

**Comment by BLumia** [comment]
Just saw [a blog that might be related to this issue written by the awesome KDABian](https://www.kdab.com/the-qt-less-traveled/)[https://www.kdab.com/the-qt-less-traveled/](https://www.kdab.com/the-qt-less-traveled/?utm_source=atom_feed) :)
