### ISSUE TITLE
hidpi support

### ISSUE THREAD

**Issue by LiohMoeller** [BLumia/pineapple-pictures#60]
The application does not seem to fully support hidpi displays on Windows. It appears as a tiny window with super small fonts and icons.

**Comment by BLumia** [comment]
What's your DPI scale level?

More detail: The Windows binary I provided is built with Qt 5, which by default will only use integer level DPI scale. So it actually does support HiDPI and for example you will get an 2x scaled window if your DPI scale level is set to >1.5.

**Comment by BLumia** [comment]
Since there is no future information provided, I'll close this issue for now.

For developers or advanced users who might be interested in Hi-DPI support in Qt, you can check out [the Environment Variable Reference section in Qt's High DPI documentation](https://doc.qt.io/qt-6/highdpi.html#environment-variable-reference) so you can know a few useful environment variables that can be handy to test the Hi-DPI support of this app (or other generic Qt app). `QT_SCALE_FACTOR` can be used to force a scale factor, and `QT_SCALE_FACTOR_ROUNDING_POLICY` explained the different default rounding policy of Qt5 and Qt6 app, since we are using Qt5 for now, `Round` is its default behavior.

For other people who might also have similar issues or other Hi-DPI related issues, please consider creating a new issue to report.

**Comment by BLumia** [comment]
Since 0.7.2, there has now been a built-in option to tweak the High-DPI rounding policy so user won't need to fiddle with environment variables. See the [High-DPI Support](https://github.com/BLumia/pineapple-pictures/wiki/High-DPI-Support) wiki page to learn more about it.
