### ISSUE TITLE
First test feedback: TIFF auto-load support

### ISSUE THREAD

**Issue by Virgus** [BLumia/pineapple-pictures#88]
Hello and congratulations for what seems a really promising picture viewer.
I just made the first tests on Windows (W7 and W10) and I'd like to share a short feedback.

A) directory with tiff files case:
- pictures open but no left and right arrows appear to scroll to the previous/next tif.

B) directory with jpg files case:
- left/right arrows work correctly
- If I try to open the directory itself I get "file is not a valid image"

C) directory with mixed tiff and jpg files case.
- opening a jpg only jpgs are "browsable"
- opening a tiff now shows the arrows. All jpgs are "browsable" together with that single tiff image. No other tiff images shows up.

Wishlists, besides the current tiff issues :
- Enable dir paths as command line parameters for those paths containing pictures
- Enable rotate counter-clockwise button
- Enable persistent rotation setting for those directories where all pictures are rotated (it might be a toggle setting lasting for a single run of the exe ?)

Thanks and have a nice day,
V.

**Comment by BLumia** [comment]
Thanks for the feedback!

> A) directory with tiff files case:
> 
> - pictures open but no left and right arrows appear to scroll to the previous/next tif.

Well, it's a known issue that I don't have a good solution right now. Currently only the suffixes in this list will be able to automatedly added to the list:

https://github.com/BLumia/pineapple-pictures/blob/a29a1806a39fef3840036eec580c11df55105b73/app/mainwindow.cpp#L58

We can add other formats to the list but we can't promise if all the listed formats are supported. For example, the pre-build Windows version that I provided supports PSD out-of-the-box, but on Linux user then needs to install KImageFormats manually to browse PSD images.

There is also a `QImageReader::supportedImageFormats()` but `jfif` is not one of the supported formats that we actually support.

> B) directory with jpg files case:
>
> - If I try to open the directory itself I get "file is not a valid image"

We don't support opening a directory directly currently. I don't find it to be very useful since this application doesn't have a folder view right now.

> C) directory with mixed tiff and jpg files case.
>
> - opening a tiff now shows the arrows. All jpgs are "browsable" together with that single tiff image. No other tiff images shows up.

This issue is the same as the first one. Maybe we should add TIFF to the list too since it's a format [directly supported by Qt](https://doc.qt.io/qt-6/qtimageformats-index.html) :)

> Wishlists, besides the current tiff issues :
>
> - Enable dir paths as command line parameters for those paths containing pictures

Same as the 2nd question.

> - Enable rotate counter-clockwise button

Is that okay if we add it as a shortcut? I don't want to put too many buttons on the bottom bar.

> - Enable persistent rotation setting for those directories where all pictures are rotated (it might be a toggle setting lasting for a single run of the exe ?)

That's a feature that we might need to think about but I don't have a proper idea right now. Persistent setting during a single session (same window) seems useful in some cases (https://github.com/BLumia/pineapple-pictures/issues/87 mentioned it could be useful to persistent image scaling), but there should be a way to let user know they are currently in such mode so users won't feel confused if thet accidently triggered such mode.

Thanks again for the feedback, and I'll submit a PR to address the TIFF loading issue later :)

**Comment by BLumia** [comment]
`.tif` and `.tiff` will now be auto loaded if they are in the same folder. You can try the CI build [here](https://ci.appveyor.com/project/BLumia/pineapplepictures/builds/47332198) or wait for the next release (maybe after a month or longer than that). Let me know if that works for you.

**Comment by Virgus** [comment]
Hello @BLumia and thanks for the prompt reply,
I'll try the CI build and let your know.

Concerning your good observation that "there should be a way to let user know they are currently in such mode so users won't feel confused", the easiest method that pops into my mind is that the buttons could have a "toggle" view. If the rotation (or the scaling as well) is permanent than the UI keeps showing the button selected.

Concerning the ccw button, might there be a config .ini file ? So that users could enable/disable parts of the UI according to their specific needs ?

Concerning the dir parameter option, I understand your point of view, but nowadays picture viewers are also used as slideshow viewers controlled by arrows or by tab/alt-tab or space-bar etc. It's a common feature that would be great on your utility too, and it's usually triggered by a single picture (like pineapple pictures already does) or by directory parameter (if the directory has image contents available).

An example is probably the tiniest slideshow player I can remember: the old and unmaintained ArtSage (formerly ArtSee)
https://web.archive.org/web/20180531134143/http://www.xworks.ca:80/artsage/index.html

Cheers,
Virginio

**Comment by BLumia** [comment]
> If the rotation (or the scaling as well) is permanent than the UI keeps showing the button selected.

It can still make people feel confused if they don't need and don't know such a feature. They might know they accidently entered some weird mode but don't know what is it and also don't know how to quit the mode.

> Concerning the ccw button, might there be a config .ini file ? So that users could enable/disable parts of the UI according to their specific needs ?

What's ccw button?

> Concerning the dir parameter option, I understand your point of view, but nowadays picture viewers are also used as slideshow viewers controlled by arrows or by tab/alt-tab or space-bar etc. It's a common feature that would be great on your utility too, and it's usually triggered by a single picture (like pineapple pictures already does) or by directory parameter (if the directory has image contents available).

Yeah, I know that, but since currently Windows doesn't let user open a directory with a user-preferred tool, and the user are probably not going to launch `ppic` from command line, so I guess adding such support is not as convenience as double-clicking the first image file from the file manager application to launch `ppic`.

------

By the way, if you can confirm the TIFF loading issue get fixed, could you create separate issues for the other feature requests you mentioned in this issue? I'd like to prefer focus on discussing a single problem per issue so it's easier to track different things in their corresponding issues, instead of discussing many different problems in a single issue. Thanks!

**Comment by BLumia** [comment]
> I thought you had a compiled version available for download and testing.

I already linked the CI build download link above (https://github.com/BLumia/pineapple-pictures/issues/88#issuecomment-1596197303), it's not a direct download link tho.

Anyway, here is the link: https://ci.appveyor.com/project/BLumia/pineapplepictures/builds/47332198 . You can either click mingw81_64_qt5_15_2 (currently recommended) or mingw_64_qt6_4, then click Artifacts, and finally download the `build\bin.zip` file.

**Comment by Virgus** [comment]
Hello Gary,
sorry I missed the "Artifacts" tab. I'm new to appveyor.com.

I got your build and more or less it works correctly. If the format and size are ok for ppic.

I got some tiff files from a book I grabbed with a Canon scanner. They were compressed in lzw and I could not open them.
So I took IrfanView and saved copies of them with different tif compressions.
A second test I made was from a pdf file. I extracted pages at different resolutions. 600 dpi tiffs were not recognized while under 300 dpi they were recognized. The software I used saves with lzw compression.

You can download a selection of my samples from here: https://we.tl/t-ykKPdQBLWG

It seems that jpg compressed tiffs are not recognized while lzw and zip compressed tiffs are ok ONLY if the size (or maybe the resolution) is under a certain value. Those named "half" are opened correctly, while the bigger ones are not recognized.

Another smaller detail came to my attention: while browsing another group of tiffs I extracted from a pdf the pdf came in the list of files cached by ppic. Showing "Image data invalid". Maybe unsupported filetypes should not be cached.

A last suggestion that pops into my mind: It would greatly help to be able to see the name of the currently visualized file: sometimes you have different versions or resolutions of a same image and it would be useful to know which one you're looking at. Maybe the feature is already available but I couldn't find a way to trigger the show-up of the file name (or the number in the list of cached files).

**Comment by BLumia** [comment]
> I got your build and more or less it works correctly. If the format and size are ok for ppic.

Seems those TIFF files were added to the "temporary gallery" but some of them failed to load as image file.

> It seems that jpg compressed tiffs are not recognized while lzw and zip compressed tiffs are ok ONLY if the size (or maybe the resolution) is under a certain value. Those named "half" are opened correctly, while the bigger ones are not recognized.

Since TIFF format itself is supported by Qt, this is an Qt upstream bug that I currently don't plan to work on. There are some bug reports in Qt's bug tracker that might related: https://bugreports.qt.io/browse/QTBUG-6870. I'll probably report them if I got some free time but you can also consider reporting the issue directly to Qt and leave a link here.

> A last suggestion that pops into my mind: It would greatly help to be able to see the name of the currently visualized file: sometimes you have different versions or resolutions of the same image and it would be useful to know which one you're looking at. Maybe the feature is already available but I couldn't find a way to trigger the show-up of the file name (or the number in the list of cached files).

Please consider creating a separate issue for a different topic. Thanks!

Since the TIFF auto-load is considered done, I'll close this one for now. Let's discuss other topic in different issue thread then :)
