### ISSUE TITLE
Rotation UI proposals

### ISSUE THREAD

**Issue by Virgus** [BLumia/pineapple-pictures#89]
Hello,
this pineapple-pictures is a really promising tool as I mentioned in another thread.

In my opinion its user experience might be improved by bi-directional rotation and rotate lock options (either by GUI buttons or by hotkeys). Here a little bit of brainstorming to see if any suggestion would find your appreciation :-)

The already available cw (clockwise) rotation button might become a toggle button so that, if any rotation is kept selected (e.g a last click longer than 500ms) the button indicates that the rotation is permanent (for that single session). Eg: clicking once the rotation button (90°) and clicking a second time while keeping the button pressed longer (rotate lock) keeps a rotation of 180° for the currently open instance. The user might see the rotation button "toggled" as a memo that the rotation lock option is set. One single extra click would unlock the rotation for the current instance and return to normal behaviour.

An optional ccw (counteclockwise) rotation button might show up if selected in a configuration ini file and give the opportunity to reproduce the same behaviour as before but in the opposite direction.
The ini file might also enable/disable the rotation lock option mentioned before for "advanced" users.

For the hotkeys proposals I just downloaded the old tool [Artsage](https://web.archive.org/web/20180531134143/http://www.xworks.ca:80/artsage/index.html) and took a snapshot. Artsage is not supported since long time and it cannot visualize all the images formats available but it implemented several features which were really useful. Even without GUI changes the hotkeys would help the ergonomics of your really nice tool.

![Rotate Ideas](https://github.com/BLumia/pineapple-pictures/assets/6388217/9cd1cd91-2921-419a-beed-ec88a6b0eae9)

Cheers,
V.

**Comment by BLumia** [comment]
For the counterclockwise rotation button, I personally prefer to add such support as a shortcut since I'd like to keep the bottom bar short enough so the application window can be scaled down to a very small size. Thus, custom shortcut support is preferred to be introduced (https://github.com/BLumia/pineapple-pictures/issues/72).

For the rotation locking mode feature, it's somewhat related to https://github.com/BLumia/pineapple-pictures/issues/87 since user might want to temporary lock other image transformation status as well. I might need to think how to introduce such feature carefully so it could be intuitive for users whether they need this feature or not.

**Comment by BLumia** [comment]
I added a new menu entry to the context menu, which can be used to avoid resetting image transformation while switching between image files. Once the menu gets checked, if you rotated, scaled, and/or flipped the image, then when you switch to the next image, the same transformation will be kept so it's also rotated, scaled, and/or flipped.

The last part of the issue is: what should the menu be called/named? I don't know any existing image viewer software are doing this and I don't have a good name in mind. Do you have any suggestions?

btw, the placeholder name I gave it right now is:

https://github.com/BLumia/pineapple-pictures/blob/d4ded92734bb44aca25e5a5a4d50b5d6f4fde4e7/app/actionmanager.cpp#L108

**Comment by Virgus** [comment]
Dear Gary,
I like the term "lock" even if it's a temporary one.
It might be "Mods Lock" or "Temp Mods Lock" or any other combination.
As an alternative "keep" would work as well "Keep Mods" or similar...

Cheers,
V.

**Comment by BLumia** [comment]
I thought about using the term "lock" but it can cause more confusion since user can still change the image transformation information while "locked" state. The "lock" only applies when switching between image files, which "Temp Mods Lock" doesn't seems deliver such information to user.

"Keep" seems better, but I'm also not sure if "Mods" is a suitable term. "Keep transformation" can be more accurate but I'm also not sure if user can know what "transformation" stands for here.

**Comment by Virgus** [comment]
I agree with your observations. Then I suppose a simpler "Keep changes" might be self explaining, with no need to mention if these are temporary or not: it'll be enough to re-launch the exe to see that those are temporary. ;-)

**Comment by BLumia** [comment]
Sorry for the long delay. The feature is now enabled since https://github.com/BLumia/pineapple-pictures/commit/9677fed3f26db0962d234e679ff88a08762476ab and will be available in the next release.

I decided to use the "Keep transformation" term and also explained it a little bit in the help dialog so I hope users won't get confused. The option is not on by default and needs the user to manually check the entry from the context menu to turn it on, so it won't be accidentally triggered by the user.

A CI build could be downloaded right now from https://ci.appveyor.com/project/BLumia/pineapplepictures/builds/48280524/job/533aj7lu9r5s0tdv/artifacts and I'll do a release probably in the next coming week :)
